### ISSUE TITLE
Decide on Location

### ISSUE THREAD

**Issue by daniel-corcoran** [linakaval/weddingsite#5]
**Top 2 Choices:** 

1. BB Riverboat (Daniel's top choice)
2. Krohn Conservatory (Lina's top choice)

**Details of each place**

1. BB Riverboat
[Wedding and rehearsal dinner packages](https://bbriverboats.com/pdf/menus-and-packages/BB_Riverboats_2024_Wedding_Packages.pdf)

It looks like they have minimums for private charter.

We would need to evaluate the size of the room and determine if it would be enough. 

![image](https://github.com/linakaval/weddingsite/assets/49919745/2a83ed96-06be-462a-a0b2-12acc965f3b3)

Pilot House Package - $90/person

![image](https://github.com/linakaval/weddingsite/assets/49919745/a236df71-d328-4107-9f88-a3e04ba43a4a)

They also offer ceremony coordinators at $700 for under 100 guests and $800 for over 100 guests. 

This doesn't include anything for rehearsal dinner - we would need to think about that (I'm not sure)

2. Krohn Conservatory

https://www.wedding-spot.com/venue/4103/Krohn-Conservatory/

https://www.cincinnati-oh.gov/cincyparks/visit-a-park/find-a-parkfacility/krohn-conservatory/

Venue rental fee is listed at $2000, all equiptment (tables, chairs, etc) are a la carte and in addition to the rental fee. 

Catering options

https://chefschoicecatering.com/
https://delightmore.com/
https://lmrcatering.com/ - Meals at/around $20, we would need to provide alcohol separately?

**Comment by linakaval** [comment]
Decided and deposit is down
